AWSTemplateFormatVersion: 2010-09-09
Description: |
  CFN Stack for Amazon Deployment Framework to divert events to Sydney region
Parameters:
  SydneyRegionLambdaARN:
    Type: String
    Default: arn:aws:lambda:ap-southeast-2:591906314725:function:CatchOrgEvent
    Description: The ARN of the Lambda function that will forward events to StepFunctions

Resources:
  CloudWatchEventsRule:
    DependsOn: ADFSNSTopic
    Type: "AWS::Events::Rule"
    Properties: 
      Description: Triggers StateMachine on Move OU
      EventPattern:
        source:
          - aws.organizations
        detail:
          eventSource:
            - organizations.amazonaws.com
          eventName:
            - MoveAccount
      Targets:
        - Arn: !Ref ADFSNSTopic
       #   RoleArn: !GetAtt StatesExecutionRole.Arn
          Id: CreateStackLinkedAccountV1

  ADFSNSTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      DisplayName: 'ADFForwardingSNS'
      TopicName: 'ADFForwardingSNS'

  ADFSNSSubscription:
    Type: "AWS::SNS::Subscription"
    DependsOn: ADFSNSTopic
    Properties:
      Endpoint: !Ref SydneyRegionLambdaARN
      Protocol: LAMBDA #required
      TopicArn: !Ref ADFSNSTopic  #required
  
  ADFSNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: MyTopicPolicy
        Version: '2012-10-17'
        Statement:
        - Sid: AllAccountEvent
          Effect: Allow
          Principal:
            AWS: "*"
          Action: 
            - SNS:GetTopicAttributes
            - SNS:SetTopicAttributes
            - SNS:AddPermission
            - SNS:RemovePermission
            - SNS:DeleteTopic
            - SNS:Subscribe
            - SNS:ListSubscriptionsByTopic
            - SNS:Publish
            - SNS:Receive
          Resource: !Ref ADFSNSTopic
          Condition:
            StringEquals:
              aws:SourceAccount: !Ref "AWS::AccountId"
        - Sid: cloudwatchEvent
          Effect: Allow
          Principal:
            Service:
            - 'events.amazonaws.com'
          Action: 
            - SNS:Publish
          Resource: !Ref ADFSNSTopic
          Condition:
            StringEquals:
              aws:SourceAccount: !Ref "AWS::AccountId"
      Topics:
      - !Ref ADFSNSTopic

  
